import { renderMarkdown } from '/help/help.js';

const el = (id) => document.getElementById(id);
const make = (tag, text, className) => { const n=document.createElement(tag); if(text!==undefined)n.textContent=text; if(className)n.className=className; return n; };
let csrf, epoch=0, currentSlug;
function status(text,error=false){el('status').textContent=text;el('status').classList.toggle('error',error);}
function clearPrivate(){epoch+=1;csrf=undefined;currentSlug=undefined;el('private').hidden=true;el('page-list').replaceChildren();el('preview').replaceChildren();}
async function api(path,{body}={}){
  const pageEpoch=epoch;const response=await fetch(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',
    headers:body===undefined?{}:{'content-type':'application/json','x-csrf-token':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const result=await response.json().catch(()=>({}));if(pageEpoch!==epoch)throw new Error('This page session has ended.');
  if(!response.ok){if(response.status===401){clearPrivate();el('signed-out').hidden=false;}
    if(response.status===403&&result.error==='mfa_required')throw new Error('Recent MFA is required. Verify, then retry publishing.');
    throw new Error({400:'Check the page fields and supported limits.',401:'Please sign in again.',403:'Platform administrator access is required.',404:'This page is not available.'}[response.status]??'The service is temporarily unavailable.');}
  return result;
}
async function action(event,operation){event?.preventDefault();const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>{b.disabled=true;});try{await operation();}catch(error){status(error.message,true);}finally{buttons.forEach(b=>{if(b.isConnected)b.disabled=false;});}}
function blank(){currentSlug=undefined;el('slug').disabled=false;for(const id of ['slug','title','summary','body-markdown'])el(id).value='';el('section').value='general';el('sort-order').value='100';el('published-state').textContent='New unpublished page';el('preview').replaceChildren();}
async function loadPage(slug){const {page}=await api(`/api/v2/admin/help/page?slug=${encodeURIComponent(slug)}`);if(!page)throw new Error('The draft is not available.');currentSlug=slug;el('slug').value=page.slug;el('slug').disabled=true;el('title').value=page.title??'';el('summary').value=page.summary??'';el('section').value=page.section;el('sort-order').value=String(page.sortOrder);el('body-markdown').value=page.bodyMarkdown??'';el('published-state').textContent=page.published?'Published (saving creates a new draft)':'Draft only';preview();for(const button of el('page-list').querySelectorAll('button'))button.classList.toggle('active',button.dataset.slug===slug);}
async function loadList(prefer){const {pages}=await api('/api/v2/admin/help');const target=el('page-list');target.replaceChildren();if(!pages.length)target.append(make('p','No managed pages yet. Static help remains available.','empty'));for(const page of pages){const button=make('button',`${page.title} · ${page.published?'published':'draft'}`);button.type='button';button.dataset.slug=page.slug;button.addEventListener('click',event=>action(event,()=>loadPage(page.slug)));target.append(button);}if(prefer&&pages.some(p=>p.slug===prefer))await loadPage(prefer);}
function preview(){renderMarkdown(el('body-markdown').value,el('preview'));}
async function save(){const page={slug:el('slug').value.trim(),section:el('section').value.trim(),sortOrder:Number(el('sort-order').value),title:el('title').value.trim(),summary:el('summary').value.trim(),bodyMarkdown:el('body-markdown').value};const result=await api('/api/v2/admin/help/save',{body:page});currentSlug=result.slug;await loadList(result.slug);status(`Draft revision ${result.revision} saved. Public help is unchanged until you publish.`);}
async function setPublished(published){const slug=currentSlug??el('slug').value.trim();if(!slug)throw new Error('Save the draft first.');await api(`/api/v2/admin/help/${published?'publish':'unpublish'}`,{body:{slug}});await loadList(slug);status(published?'The current draft is now public.':'The managed page is no longer public; the static help page remains.');}
async function startMfa(){const {redirectTo}=await api('/auth/step-up',{body:{}});const destination=new URL(redirectTo);if(destination.protocol!=='https:'||destination.username||destination.password)throw new Error('Invalid verification destination.');clearPrivate();location.assign(destination.href);}
el('new-page').addEventListener('click',event=>action(event,async()=>{blank();status('Enter a URL slug and save the first draft.');}));el('editor-form').addEventListener('submit',event=>action(event,save));el('publish').addEventListener('click',event=>action(event,()=>setPublished(true)));el('unpublish').addEventListener('click',event=>action(event,()=>setPublished(false)));el('preview-button').addEventListener('click',event=>action(event,async()=>preview()));el('verify-mfa').addEventListener('click',event=>action(event,startMfa));el('signout').addEventListener('click',event=>action(event,async()=>{await api('/auth/logout',{body:{}});clearPrivate();el('signed-out').hidden=false;status('Signed out.');}));
addEventListener('pagehide',clearPrivate);addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
(async()=>{try{const response=await fetch('/auth/session',{credentials:'same-origin',cache:'no-store'});if(response.status===404){status('Platform administration is not enabled on this deployment.');return;}if(response.status===401){el('signed-out').hidden=false;status('Sign in as a platform administrator.');return;}if(!response.ok)throw new Error('Secure sign-in is temporarily unavailable.');const session=await response.json();if(!session.portalEnabled||!session.platformAdministrator){status('This account is not a platform administrator.',true);return;}csrf=session.csrfToken;el('private').hidden=false;el('who').textContent=`Signed in as ${session.user.displayName}`;const expiry=new Date(session.mfaExpiresAt);el('mfa-note').textContent=expiry.getTime()>Date.now()?`MFA verified until ${expiry.toLocaleTimeString()}.`:'MFA is required to save or publish.';blank();await loadList();status('Help publishing console ready.');}catch(error){status(error.message,true);}})();
